In [34]:
import pandas as pd

In [57]:
df = pd.read_csv('../Sales-[5444].csv')

In [36]:
df.shape

(1000, 10)

In [37]:
df.head()

,Item_Name,details,Catatory,price,priceWithCurrency,available,text,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,NaN,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,NaN,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,NaN,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,NaN,NaN,Limited quantity available / 156 sold,NaN,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"

In [38]:
df.tail()

,Item_Name,details,Catatory,price,priceWithCurrency,available,text,sold,lastUpdated,itemLocation
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,45.0,"45 available / 1,613 sold",1613.0,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,10.0,More than 10 available / 31 sold,31.0,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2.0,2 available / 305 sold,305.0,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2.0,2 available / 22 sold,22.0,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,10.0,More than 10 available / 24 sold,24.0,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Item_Name          999 non-null    str
 1   details            1000 non-null   str
 2   Catatory           997 non-null    str
 3   price              995 non-null    float64
 4   priceWithCurrency  999 non-null    str
 5   available          889 non-null    float64
 6   text               997 non-null    str
 7   sold               992 non-null    float64
 8   lastUpdated        947 non-null    str
 9   itemLocation       1000 non-null   str
dtypes: float64(3), str(7)
memory usage: 78.3 KB

In [56]:
df.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
item_name,1000,247,Giorgio Armani,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
details,1000,966,Hawas for him Eau De Parfum By Rasasi 100ml 3....,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
catatory,1000,64,Eau de Toilette,444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,1000.0,NaN,NaN,NaN,46.4812,3.0,22.99,35.71,59.0,259.09,35.527862
pricewithcurrency,1000,685,US $29.99/ea,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
available,889.0,NaN,NaN,NaN,20.046119,2.0,5.0,10.0,10.0,842.0,61.547985
text,1000,759,More than 10 available / 16 sold,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sold,1000.0,NaN,NaN,NaN,769.441,1.0,14.0,49.5,317.5,54052.0,3199.202862
lastupdated,947,933,"May 24, 2024 10:26:59 PDT",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
itemlocation,1000,276,"Dallas, Texas, United States",126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lastupdated_dt,947,NaN,NaN,NaN,2024-05-15 21:31:59.559662,2022-10-20 18:26:14,2024-05-18 08:30:40.500000,2024-05-22 16:32:56,2024-05-24 00:01:38.500000,2024-05-24 10:27:08,NaN

In [41]:
column_names = df.columns

column_names

Index(['Item_Name', 'details', 'Catatory', 'price', 'priceWithCurrency',
       'available', 'text', 'sold', 'lastUpdated', 'itemLocation'],
      dtype='str')

In [42]:
column_names = [c.lower() for c in df.columns]

df.columns = column_names

df.columns

Index(['item_name', 'details', 'catatory', 'price', 'pricewithcurrency',
       'available', 'text', 'sold', 'lastupdated', 'itemlocation'],
      dtype='str')

# Understand the data

- Handling Missing Values and Placeholders.
- Handling Duplicates.

### Handling Missing Values and Placeholders

In [43]:
df.isna().sum()

item_name              1
details                0
catatory               3
price                  5
pricewithcurrency      1
available            111
text                   3
sold                   8
lastupdated           53
itemlocation           0
dtype: int64

In [44]:
total_missing_nums = df.isna().sum().sum()

print(f'Total missing numbers: {total_missing_nums}')

Total missing numbers: 185

In [45]:
percentage_isna = round((100* total_missing_nums/df.shape[0]), 3)

print(f'Percentage of Missing Numbers: {percentage_isna}%.')

Percentage of Missing Numbers: 18.5%.

18.5% of the data will be lost if each row having a missing value is dropped. That is a huge amount of data to be lost. Also, since some of the columns that have missing values are text, they cannot be imputed with 0s or median value. Available column has 111 missing values and really needs to be studied because generalizing and imputing it with 0s or median value would drastically alter the quality of the data.

In [46]:
mask = df['price'].isna() | (df['pricewithcurrency'].isna()  | df['pricewithcurrency'] == 'Unknown')


print(df.loc[mask, ['item_name', 'price', 'pricewithcurrency']])

          item_name  price pricewithcurrency
1           AS SHOW    NaN        US $109.99
3    Giorgio Armani    NaN      US $44.99/ea
10     Ralph Lauren    NaN      US $34.99/ea
13          As Show    NaN      US $59.99/ea
20  Dolce & Gabbana    NaN      US $29.94/ea

C:\Users\Jefferson\AppData\Local\Temp\ipykernel_48196\882630094.py:1: Pandas4Warning: 'or' operations between boolean dtype and str are deprecated and will raise in a future version. Explicitly cast the strings to a boolean dtype before operating instead.
  mask = df['price'].isna() | (df['pricewithcurrency'].isna()  | df['pricewithcurrency'] == 'Unknown')

In [47]:
# Handling missing values in item_name, catatory, text, pricewithcurrency

unknown_cols = ['item_name', 'catatory', 'text', 'pricewithcurrency']

for uc in unknown_cols:
    df[uc] = df[uc].fillna('Unknown')

df.isna().sum()

item_name              0
details                0
catatory               0
price                  5
pricewithcurrency      0
available            111
text                   0
sold                   8
lastupdated           53
itemlocation           0
dtype: int64

Handling Price. If price is not available and pricewithcurrency is avaialable, the price can be inferred from the pricewithcurrency

In [48]:
extract_price = (
    df['pricewithcurrency']
    .astype(str)
    .str.replace(',', '', regex=False)       
    .str.extract(r'(\d+\.?\d*)')[0]         
    .astype(float)
)

df['price'] = df['price'].fillna(extract_price)

In [49]:
df.isna().sum()

item_name              0
details                0
catatory               0
price                  0
pricewithcurrency      0
available            111
text                   0
sold                   8
lastupdated           53
itemlocation           0
dtype: int64

In [50]:
df.head()

,item_name,details,catatory,price,pricewithcurrency,available,text,sold,lastupdated,itemlocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,NaN,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,Unknown,NaN,Limited quantity available / 156 sold,NaN,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"

In [51]:
# Handling sold

df['sold'] = df['sold'].fillna(df['sold'].median())

df.isna().sum()

item_name              0
details                0
catatory               0
price                  0
pricewithcurrency      0
available            111
text                   0
sold                   0
lastupdated           53
itemlocation           0
dtype: int64

In [52]:
print(df['lastupdated'].dropna().head(10).tolist())
print(df['lastupdated'].str.extract(r'([A-Za-z]{2,4})$')[0].value_counts(dropna=False))

['May 24, 2024 10:03:04 PDT', 'May 23, 2024 23:07:49 PDT', 'May 22, 2024 21:55:43 PDT', 'May 24, 2024 03:30:43 PDT', 'May 24, 2024 07:56:25 PDT', 'May 23, 2024 06:57:41 PDT', 'May 16, 2024 13:42:49 PDT', 'May 24, 2024 00:10:39 PDT', 'May 24, 2024 09:08:14 PDT', 'May 23, 2024 07:21:23 PDT']
0
PDT    932
NaN     53
PST     15
Name: count, dtype: int64

In [53]:
cleaned = df['lastupdated'].str.replace(r'\s+[A-Za-z]{2,4}$', '', regex=True)

df['lastupdated_dt'] = pd.to_datetime(cleaned, format='%b %d, %Y %H:%M:%S', errors='coerce')

In [54]:
df.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
item_name,1000,247,Giorgio Armani,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
details,1000,966,Hawas for him Eau De Parfum By Rasasi 100ml 3....,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
catatory,1000,64,Eau de Toilette,444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,1000.0,NaN,NaN,NaN,46.4812,3.0,22.99,35.71,59.0,259.09,35.527862
pricewithcurrency,1000,685,US $29.99/ea,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
available,889.0,NaN,NaN,NaN,20.046119,2.0,5.0,10.0,10.0,842.0,61.547985
text,1000,759,More than 10 available / 16 sold,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sold,1000.0,NaN,NaN,NaN,769.441,1.0,14.0,49.5,317.5,54052.0,3199.202862
lastupdated,947,933,"May 24, 2024 10:26:59 PDT",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
itemlocation,1000,276,"Dallas, Texas, United States",126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lastupdated_dt,947,NaN,NaN,NaN,2024-05-15 21:31:59.559662,2022-10-20 18:26:14,2024-05-18 08:30:40.500000,2024-05-22 16:32:56,2024-05-24 00:01:38.500000,2024-05-24 10:27:08,NaN

In [55]:
df.head(30)

,item_name,details,catatory,price,pricewithcurrency,available,text,sold,lastupdated,itemlocation,lastupdated_dt
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,49.5,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",2024-05-24 10:03:04
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",2024-05-23 23:07:49
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",2024-05-22 21:55:43
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",2024-05-24 03:30:43
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,Unknown,NaN,Limited quantity available / 156 sold,49.5,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",2024-05-24 07:56:25
5,Multiple Brands,Men's Perfume Sampler 10pcs Sample Vials Desig...,Perfume,14.99,US $14.99,10.0,More than 10 available / 79 sold,79.0,"May 23, 2024 06:57:41 PDT","Houston, Texas, United States",2024-05-23 06:57:41
6,Maison Alhambra,Glacier Bold by Maison Alhambra 3.4oz EDP for ...,Eau de Parfum,30.99,US $30.99/ea,9.0,9 available / 39 sold,39.0,"May 16, 2024 13:42:49 PDT","Englewood Cliffs, New Jersey, United States",2024-05-16 13:42:49
7,Unbranded,Parfums De-Marly-Haltane Eau de Parfum spray 4...,Eau de Parfum,85.00,US $85.00,NaN,Last One / 6 sold,7654.0,"May 24, 2024 00:10:39 PDT","Ithaca, New York, United States",2024-05-24 00:10:39
8,Unbranded,Hawas for him Eau De Parfum By Rasasi 100ml 3....,/,15.89,US $15.89,10.0,10 available / 17 sold,17.0,"May 24, 2024 09:08:14 PDT","shanghai, China",2024-05-24 09:08:14
9,Gucci,Gucci Guilty for Him - Classic 3oz Eau de Toil...,Eau de Parfum,49.99,US $49.99/ea,8.0,8 available / 68 sold,68.0,"May 23, 2024 07:21:23 PDT","Dearborn Heights, Michigan, United States",2024-05-23 07:21:23
10,Ralph Lauren,Polo Blue by Ralph Lauren 4.2 oz EDT Cologne f...,Eau de Toilette,34.99,US $34.99/ea,10.0,More than 10 available / 615 sold,615.0,"May 24, 2024 07:53:23 PDT","Ecorse, Michigan, United States",2024-05-24 07:53:23
11,Dolce&Gabbana,Dolce & Gabbana Light Blue Men 4.2 oz / 125 mL...,Eau de Toilette,29.95,US $29.95/ea,7.0,7 available / 458 sold,458.0,"May 23, 2024 08:37:49 PDT","Warren, Michigan, United States",2024-05-23 08:37:49
12,SECERTMU,New 2024 Sexy Cologne Cupid Hypnosis Long Last...,Perfume,15.99,US $15.99,10.0,More than 10 available / 889 sold,889.0,"May 21, 2024 19:20:12 PDT","San Francisco, California, United States",2024-05-21 19:20:12
13,As Show,Sauvage Eau de Parfum Spray For Men 3.4 Oz/100...,Eau de Parfum,59.99,US $59.99/ea,9.0,9 available / 63 sold,63.0,"May 23, 2024 03:08:18 PDT","Dayton,New Jersey, Hong Kong",2024-05-23 03:08:18
14,Versace,Eau Fraiche By Versace 3.4 oz 100 ml Eau de To...,Eau de Toilette,34.99,US $34.99/ea,7.0,7 available / 136 sold,136.0,"May 24, 2024 00:02:27 PDT","Warren, Michigan, United States",2024-05-24 00:02:27
15,Paco Rabanne,1 Million by Paco Rabanne 3.4 Fl oz / 100 ml P...,PARFUM,68.99,US $68.99/ea,2.0,2 available / 20 sold,20.0,"May 24, 2024 02:41:49 PDT","San Jose, California, United States",2024-05-24 02:41:49
16,Grandeur,Tribal Intense by Grandeur - Eau de Parfum for...,Eau de Parfum,37.99,US $37.99,10.0,More than 10 available / 44 sold,44.0,"May 24, 2024 08:14:43 PDT","Miami, Florida, United States",2024-05-24 08:14:43
17,Armaf,Club de Nuit Intense by Armaf 3.6 oz EDT Colog...,Eau de Toilette,29.99,US $29.99/ea,5.0,5 available / 384 sold,384.0,"May 24, 2024 05:13:20 PDT","Hamtramck, Michigan, United States",2024-05-24 05:13:20
18,Carolina Herrera,Carolina Herrera 212 NYC Men's Cologne EDT 3.4...,Eau de Toilette,39.99,US $39.99/ea,10.0,More than 10 available / 236 sold,236.0,"May 23, 2024 08:48:22 PDT","Flat Lick, Kentucky, United States",2024-05-23 08:48:22
19,Dior,Dior Sauvage Eau de Toilette 3.4 Oz 100ml Bran...,Eau de Toilette,83.95,US $83.95,4.0,4 available / 22 sold,22.0,"May 22, 2024 14:31:55 PDT","Elmhurst, New York, United States",2024-05-22 14:31:55
20,Dolce & Gabbana,Light Blue by Dolce & Gabbana 4.2 oz Cologne f...,Eau de Toilette,29.94,US $29.94/ea,NaN,"Limited quantity available / 9,208 sold",9208.0,"May 23, 2024 20:04:11 PDT","Hackensack, New Jersey, United States",2024-05-23 20:04:11
21,Clinique,CLINIQUE HAPPY Pour Homme Cologne edt for Men ...,Eau de Toilette,21.99,US $21.99/ea,4.0,4 available / 86 sold,86.0,"May 21, 2024 14:28:23 PDT","Miami, Florida, United States",2024-05-21 14:28:23
22,Dumont,Dumont Men's Nitro Red EDP Spray 3.4 oz Fragra...,Fragrances,49.99,US $49.99,3.0,3 available / 187 sold,187.0,"May 24, 2024 09:02:39 PDT","Brooklyn, New York, United States",2024-05-24 09:02:39
23,Afnan,Turathi Blue by Afnan for men EDP 3oz New in S...,Eau de Parfum,33.70,US $33.70,10.0,More than 10 available / 131 sold,131.0,"May 21, 2024 14:00:54 PDT","Dallas, Texas, United States",2024-05-21 14:00:54
24,Versace,Versace Eros by Gianni Versace 3.4oz EDT Colog...,Eau de Toilette,35.99,US $35.99,2.0,2 available / 43 sold,43.0,"May 24, 2024 00:13:55 PDT","Pomona, California, United States",2024-05-24 00:13:55
25,Azzaro,Azzaro The Most Wanted 3.3 oz./100 ml. PARFUM ...,Parfum,89.97,US $89.97/ea,10.0,10 available / 920 sold,920.0,"May 24, 2024 08:32:16 PDT","Katy, Texas, United States",2024-05-24 08:32:16
26,Unbranded,USA Parfums de Marly Layton Royal Essence 4.2 ...,Eau de Parfum,92.99,US $92.99,5.0,5 available / 19 sold,19.0,"May 24, 2024 00:01:17 PDT","College Point, New York, United States",2024-05-24 00:01:17
27,Azzaro,Azzaro The Most Wanted 3.38 oz./100 ml. PARFUM...,Eau de Parfum,87.99,US $87.99,2.0,2 available / 4 sold,4.0,NaN,"NEW YORK, United States",NaT
28,Giorgio Armani,Acqua Di Gio Profumo by Giorgio Armani 4.2oz C...,Eau de Parfum,119.99,US $119.99,10.0,10 available / 34 sold,34.0,"May 24, 2024 07:16:53 PDT","New York,USA, Hong Kong",2024-05-24 07:16:53
29,Penhaligon's,Penhaligon's The Tragedy of Lord George 2.5oz ...,Eau de Parfum,99.99,US $99.99,NaN,Last One / 30 sold,30.0,"May 20, 2024 04:16:27 PDT","Brenham, Texas, United States",2024-05-20 04:16:27